config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :vets
  resources :photos
  
  resources :vets do
    resources :reservations, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    post '/like' => 'likes#like_toggle'
  end

  resources :conversations, only: [:index, :create, :show] do
    resources :messages, only: [:index, :create, :show]
  end
  
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :users
  resources :examinations

  get '/search' => 'pages#search'
  get '/searchreview' => 'pages#searchreview'
  get 'searchstar' => 'pages#searchstar'
  
  get '/introduction' => 'pages#introduction'
  resources :pages
  # devise_for :users do
  # get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@conversations = Conversation.involving(current_user)
	end

	def create
		if Conversation.between(params[:sender_id], params[:recipient_id]).present?
			@conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
		else
			@conversation = Conversation.create(conversation_params)
		end

		redirect_to conversation_messages_path(@conversation)
	end
	
	def show
		@vet = Vet.find(params[:id])
		@users = User.all
		@conversations = Conversation.involving(current_user)
	end

	private

		def conversation_params
			params.permit(:sender_id, :recipient_id)
		end

end

app/views/conversations/index.html.erb
<div class="row">
	<div class="reservation_index">
  <div class="row">
    <div class="col-xl-3 col-md-3 indexleft" id="reservation_left">
      <div class="left_hospitalpic">
        <%= image_tag("vet01", class: "reservation_hospitalpic", :alt => "first slide")  %>
      <div class="left_hospitalinfo">
        <p class="reservation_hospitalname">도토 동물병원</p> <!--병원 이름/정보/사진 불러오기 기능 넣어주세요!-->
        <p>번호:</p>        
        <p>주소: 서울특별시 성북구 안암동 뭐시기</p>
        <p>특이사항: 24시간, 응급실 운영</p>
      </div>z
      </div>
    </div>

    <div class="col-xl-9 col-md-9 col-xs-12 indexright" id="reservation_right">
      <div class="row">
        <div class="col-1">
        </div>
        
        <div class="col-11">
          <p class="writereview">예약 상담</p><!--1:1 채팅기능 넣어주세요!-->
          <div class="container_reservation">
          	<!-- 채팅창 기능 시작-->
				    <div class="panel panel-default">
							<div class="panel-heading">Your conversations</div>
							<div class="panel-body">
								<div class="container">
									<% @conversations.each do |conversation| %>
										<% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>
				
										<%= link_to conversation_messages_path(conversation) do %>
				
											<div class="row conversation">
												<div class="col-md-2">
													<%= other.name %><br>
												</div>
												<div class="col-md-8">
												</div>
											</div>
				
										<% end %>
									<% end %>
								</div>
							</div>
						</div>
				
						<h3>All Users</h3>
						<% @users.each do |user| %>
							<% if user.vets.count > 0 %>
								<%= user.name %>
								<%= user.vets[0].vtitle %>
								<%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' %>
							<% end %>
							<br>
						<% end %>
						<!--채팅 기능 끝-->
          </div>
        </div>
        
      </div>
    </div>
    
  </div>
	</div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script type="text/javascript">

  $( function() {
    $( "#datepicker" ).datepicker();
  
  } );

$( function() {
    $( "#timepicker" ).timepicker();
  
  } );







  // $(function() {
  //   $('#datetimepicker3').datetimepicker({
  //     pickDate: false
  //   });
  // });
</script>

app/views/conversations/show.html.erb
<div class="messagecontainerbody">
<div class="intro">
  <%= image_tag("intro0", class: "imgintro0", :alt => "first slide")  %>
  <div class="introslogan">
    <p>예약 상담</p>
  </div>
</div>


<div id="conversation-wrap">
<div class="row"> <!-- showcontainer 6:6 row -->

  <div class="col-xl-4 col-md-4" id="showleft">
    <div class= "showhospitaltext">
      <div class= "hospitaltitle">
        <div class="vettitle_show">
          <div class="conversation_vettitle"><%= @vet.vtitle %></div>
        </div>
        <!--<span class= "score"> 3.5 </span>-->

      </div><!-- hospitaltitle 끝 -->
              
      <div class= "hospitalinfo">
        <div class= "row"> <!-- hospitalinfo row 6:6 ... infolist, pricelist  -->
          <div class= "col-xl-12 col-md-12 infolist">
            <div class="indexline"> 
            <br>
              <div class= "basicinfohead">기본정보</div>
            </div>  <!-- indexline 끝 -->
            <div class="indexline">
              <div class= "row">
                <div class= "col-4 indexicon">
                  <div class= "icon">병원주소</div>
                </div>
                <div class= "col-8 indexicontext">
                  <div class = "address"><%= @vet.address %></div>
                </div>
              </div> <!-- row 끝 -->
            </div>  <!-- indexline 끝 -->
            <div class="indexline">
              <div class= "row">
                <div class= "col-4 indexicon">
                  <div class= "icon">병원전화</div>
                </div>
                <div class= "col-8 indexicontext">
                  <div class = "telephone"><%= @vet.telephone %></div>
                </div>
              </div> <!-- row 끝 -->
            </div> <!-- indexline 끝 -->
           
            <div class="indexline">
              <div class= "row">
                <div class= "col-4 indexicon">
                  <div class= "icon">추가정보</div>
                </div>
                <div class= "col-8 indexicontext">
                  <div class="amenities"> <!-- 리스트 span으로 바꿈 --> 
      							<span class="<%= 'text-line-through' if !@vet.hotel %>">호텔 /</span>
      							<span class="<%= 'text-line-through' if !@vet.supply %>">용품 판매 /</span>
      							<span class="<%= 'text-line-through' if !@vet.hour %>">24시간 진료 /</span>
      							<span class="<%= 'text-line-through' if !@vet.beauty %>">미용</span>
  	              </div>
                </div>
              </div> <!-- row 끝 -->
            </div> <!-- indexline 끝 -->
            
            <div class="indexline">
              <div class= "row">
                <div class= "col-4 indexicon">
                  <div class= "icon">특이사항</div>
                </div>
                <div class= "col-8 indexicontext">
                  <div class = "moreinfo"><%= @vet.description %></div>
                </div>
              </div> <!-- row 끝 -->
            </div> <!-- indexline 끝 -->
            
            <div class="indexline">
              <div class= "row">
                <div class= "col-4 indexicon">
                  <div class= "icon">홈페이지</div>
                </div>
                <div class= "col-8 indexicontext">
                  <div class ="homepage">
                    <a href="<%= @vet.homepage %>"><%= @vet.homepage %></a>
                  </div>
                </div>
              </div> <!-- row 끝 -->
            </div> <!-- indexline 끝 -->
          </div>
        </div>
      </div>
      
  </div>
</div>

    <div class="col-xl-8 col-md-8 col-xs-8" id="reservation_right">
      <div class="row">
          <!--<div class="writereview">예약 상담</div>-->
          <hr>
        <div class="col-6">
        
          <div class="container_reservation">
          	<!-- 채팅창 기능 시작-->
				    <div class="panel panel-default">
				      <div class="row">
				        <div class="col-12">
							   <div class="panel-heading">예약 상담 히스토리</div>
							  </div>
							</div>
							<div class="panel-body">
				<div class="container">
					<% @conversations.each do |conversation| %>
						<% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>
						<%= link_to conversation_messages_path(conversation) do %>
							<div class="row conversation">
							  <div class="conversation_othername">
								<div class="col-md-2">
									<%= other.name %><br>
								<!--라스트 콘텐트-->
								</div>
							</div>	
								<div class="col-md-8">
								라스트 메세지 타임 
								</div>
							</div>

						<% end %>
					<% end %>
				</div>
			</div>
		</div>

				            
								
								</div>
							</div>
				<div class="col-6">
				  <div class="panel-heading">누구에게 메세지를 보내시겠어요?</div>
				  <div class="panel-body">
						<% @users.each do |user| %>
							<% if user.vets.count > 0 %>
							  <div class="convlist">
							    <div class="row indexline">
							      <div class="col-8 convlist_vettitle">
							     
						        	<%= user.name %>
							       	<%= user.vets[0].vtitle %>
							    	</div>
							    	<div class="col-4">
							      	<div class="text-center convbtn"><i class="fa fa-plus-circle" aria-hidden="true"></i><%= link_to "1:1 상담하기", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' %>
								</div>
							    	</div>
								  </div>
								</div>
							<% end %>
						<% end %>
						<!--채팅 기능 끝-->
        </div>
        
      </div>			
						</div>
		
    </div>
    
  </div>
</div>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script type="text/javascript">

  $( function() {
    $( "#datepicker" ).datepicker();
  
  } );

$( function() {
    $( "#timepicker" ).timepicker();
  
  } );







  // $(function() {
  //   $('#datetimepicker3').datetimepicker({
  //     pickDate: false
  //   });
  // });
</script>