config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :vets
  resources :photos
  
  resources :vets do
    resources :reservations, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    post '/like' => 'likes#like_toggle'
  end

  resources :conversations, only: [:index, :create, :show] do
    resources :messages, only: [:index, :create, :show]
  end
  
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :users
  resources :examinations

  get '/search' => 'pages#search'
  get '/searchreview' => 'pages#searchreview'
  get 'searchstar' => 'pages#searchstar'
  
  get '/introduction' => 'pages#introduction'
  resources :pages
  # devise_for :users do
  # get ':user/edit-profile' => 'devise/registration#edit', :as => :edit_user_profile
  # end
end

app/models/ability.rb
class Abilityinclude CanCan::Ability
  
  def initialize(user) 
    user ||= User.new 
    can :manage, :all if user.role == "관리자" 
    
    if user.role =="수의사"
    can :read, :all
    can :new, :all
    can :create, :all
    can :manage, Vet, user_id: user.id
    
    
    if user.role =="일반고객"
     can :read, :all
      can :new, :all
      can :create, :all
      can :update, Review, user_id: user.id
      can :delete, Review, user_id: user.id
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

end

app/models/examination.rb
class Examination < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :vet
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :vet
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :vet
end

app/models/review.rb
class Review < ApplicationRecord
   paginates_per 5
  
  belongs_to :vet
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  
  # after_create :update_vet_rating

  # def update_vet_rating
  #   vet.update_average
  # end

  private
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  validates :phone_number, presence: true, uniqueness: true, length: { is: 11 }  
  validates :address, presence: true
  validates :birth_date, presence: true
  ROLES = %w[일반고객 수의사 관리자]
  has_many :vets, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :examinations, dependent: :destroy
  has_many :likes
  has_many :liked_vets, through: :likes, source: :vet
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  

  def is_like?(vet)
    Like.find_by(user_id: self.id, vet_id: vet.id).present?
  end
  
  def name
    email.split('@')[0]
  end  
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name
    end
  end  
  
end

app/models/vet.rb
class Vet < ApplicationRecord
  paginates_per 5
  
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :photos
  has_many :reviews
  has_many :reservations
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  validates :address, presence: false
  validates :telephone, presence: false
  validates :description, presence: false
  validate  :picture_size

  
  
  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

  # def update_average
  #   @value = 0
  #   self.reviews.star.each do |star|
  #     @value = @value + star.value
  #   end
  #   @total = self.reviews.star.size


  #   update_attributes(average: @value.to_f / @total.to_f)
  # end

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]
  
  def index
    @vets = current_user.vets
  end

  def show
    @vets = Vet.find(params[:id])
    @photos = @vet.photos
    @reviews = @vet.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
    @reviewsp = @reviews.order(:created_at).page params[:page] #일단 이렇게
   
  end

  def new
    @vet = current_user.vets.build
  end

  def create
    @vet = current_user.vets.build(vet_params)
    
    if @vet.save
      if params[:images]
        params[:images].each do |image|
          @vet.photos.create(image: image)
        end
      end
      @photos = @vet.photos
      redirect_to edit_vet_path(@vet), notice: "Saved"
    else
      render :new
    end
  end



  def update
    if @vet.update(vet_params)
      if params[:images]
        params[:images].each do |image|
          @vet.photos.create(image: image)
        end
      end
      
      redirect_to edit_vet_path(@vet), notice: "Updated.."
    else
      render :edit
    end
  end
  
  private
  
    def set_vet
      @vet = Vet.find(params[:id])
    end
    
    def vet_params
      params.require(:vet).permit(:vtitle, :postcode, :address, :address_detail, :telephone, :description, :hour, :hotel, :beauty, :supply, :homepage, :user_id, :picture)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/shared/_carousel-admin.html.erb
<div class="container text-center my-3">
    <div class="row mx-auto my-auto">
        <div id="adminCarousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <%= image_tag("character01.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("character02.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
                <div class="carousel-item">
                   <%= image_tag("character03.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
                <div class="carousel-item">
                   <%= image_tag("character01.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
                <div class="carousel-item">
                   <%= image_tag("character02.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
                <div class="carousel-item">
                   <%= image_tag("character03.png" , class:"d-block col-4 img-fluid admincarouselimg") %>
                </div>
            </div>
            <a class="carousel-control-prev" href="#recipeCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#recipeCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            <a class="carousel-control-prev" href="#adminCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#adminCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>


<script type="text/javascript">

 $('#recipeCarousel').carousel({
  interval: 10000
})

$('.carousel .carousel-item').each(function(){
    var next = $(this).next();
    if (!next.length) {
    next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));
    
    if (next.next().length>0) {
    next.next().children(':first-child').clone().appendTo($(this));
    }
    else {
      $(this).siblings(':first').children(':first-child').clone().appendTo($(this));
    }
}); 



 
    $('#like-unlike').click(function() {
     $(this).toggleClass('fa-heart-o fa-heart');
    });

</script>

app/views/shared/_carousel-show.html.erb
<div class="container text-center my-3">
    <div class="row mx-auto my-auto">
        <div id="showCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <%= image_tag("vet01.jpg" ,class: "d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("vet02.jpg" ,class:"d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("vet03.jpg" ,class:"d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("vet04.jpg" ,class:"d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("vet05.jpg" ,class:"d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
                <div class="carousel-item">
                    <%= image_tag("vet06.jpg" ,class:"d-block col-4 img-fluid practiceimg", :alt => "first slide") %>
                </div>
            </div>
            <a class="carousel-control-prev" href="#showCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#showCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<script>
$('#showCarousel').carousel({
  interval: 10000
})

$('.carousel .carousel-item').each(function(){
    var next = $(this).next();
    if (!next.length) {
    next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));
    
    if (next.next().length>0) {
    next.next().children(':first-child').clone().appendTo($(this));
    }
    else {
      $(this).siblings(':first').children(':first-child').clone().appendTo($(this));
    }
});

</script>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
   
    <p>&copy; DontBeSick, Doto from KUlikelion5th</p>
    <p id="editrequest"data-toggle="modal" data-target="#editrequestModal">정보 수정 요청하기</p>
  </div>
  
   <div class="modal fade" id="editrequestModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                      <div class="modal-content">
                      <div class="modal-header">
                       <h5 class="modal-title" id="exampleModalLabel">정보 수정요청</h5>
                  
                       
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                       </button>
                      </div>
                      <div class="modal-body">
                       
                         
                         <textarea class="form-control input-lg" autofocus="" rows="2" placeholder="요청자 이름"></textarea>
                         <br>
                         
                        <textarea class="form-control input-lg" autofocus="" rows="2" placeholder="요청자 이메일"></textarea>
                         <br>
                         
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
   가격 수정
  </label>
</div>

<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
   병원 주소 수정
  </label>
</div>

<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
   병원 폐업 여부 수정
  </label>
</div>

<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
   병원 정보 수정
  </label>
</div>

<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
   기타 수정
  </label>
</div>

                
                        <textarea class="form-control input-lg" autofocus="" rows="4" placeholder="잘못된 정보를 입력해주세요. 정확하고 건강한 피드백은 사이트를 이롭게 합니다~~ "></textarea>
                         <br>
                 <div class="form-group">
                     <span class="btn btn-default btn-file">
                         <i class="fa fa-cloud-upload fa-lg"></i> 사진 올리기
                         <%= file_field_tag "images[]", type: :file, multiple: true %>
                     </span>
                 </div>
                       <br>
                        
                          
                        </div>
                        <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                     <button type="button" class="btn btn-secondary">저장</button>
                     </div>
 
                        
              
                      </div>
                     
                     </div>
                     </div>
                     </div>
</footer>

app/views/shared/_modal-addprice.html.erb
<div class="modal fade" id="addpriceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                      <div class="modal-content">
                      <div class="modal-header">
                       <h5 class="modal-title" id="exampleModalLabel">가격 추가하기</h5>
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                       </button>
                      </div>
                      <div class="modal-body">
                      <textarea class="form-control input-lg" autofocus="" placeholder="항목이름"></textarea>
               <br>
                <textarea class="form-control input-lg" autofocus="" placeholder="가격"></textarea>
                <br>
                
                      </div>
                      <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                     <button type="button" class="btn btn-primary">저장</button>
                     </div>
                     </div>
                     </div>
                     </div>
                    

app/views/shared/_modal-addreservation.html.erb
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">


<div id="addreservationModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
			예약하기
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      
        <div class="modal-body">
          <%= form_for([@vet, @vet.reservations.new]) do |f| %>
  
        <div class="review_form"> 
      
          <div class="datetimepicker">
            <div class="form_group">
              <%= f.text_field :reserved_date, id: 'datetimepicker', placeholder: "클릭해서 시간을 선택하세요." %>
            </div>
          </div>
        </div>
          <br>
        
          <%= f.hidden_field :vet_id, value: @vet.id %>
          <br>
        </div>
      

      <div class="modal-footer">
        <br>
        <div class="actions">
          <%= f.submit "제출하기", class: "btn btn-secondary submitbutton" %>
        </div>
          <ul class="pull-left list-inline"><li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li><li><a href=""><i class="glyphicon glyphicon-camera"></i></a></li><li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li></ul>
		  </div>	
		  </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_modal-addreview.html.erb
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">


<div id="addreviewModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
			새 리뷰 작성
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <%= form_for([@vet, @vet.reviews.new]) do |f| %>

<div class="review_form">

  <div id="user_stars"></div>
<h4> 한줄평 </h4>
<div class="form_group">
  <%= f.text_area :comment , rows: 1, class: "form-control" , placeholder:'최고의 병원입니다~' %>  
</div>
<br>


<h4> 진료 동물 </h4>
<div class="form_group">
  <%= f.text_area :reviewanimal, rows: 1, class: "form-control" , placeholder:'고양이 - 6살, 중성화 남 ' %>  
</div>
<br>


<h4> 진료 내역 </h4>
<div class="form_group">
  <%= f.text_area :treatment, rows: 3, class: "form-control" , placeholder:'기본 진료, 발톱 깎기, 피부병 ' %>  
</div>
<br>


<h4> 자유 리뷰 </h4>
<div class="form_group">
  <%= f.text_area :reviewmore, rows: 5, class: "form-control", placeholder: "자유롭게 후기를 남겨주세요." %>
</div>

<div> 
  <span class="picture">
    <%= f.file_field :picture,  class:"addpicbutton", accept: 'image/jpeg,image/gif,image/png' %>
  </span>
</div>

<%= f.hidden_field :vet_id, value: @vet.id %>
<br>


</div>



      </div>
      <div class="modal-footer">

        <div class="actions">
  <%= f.submit "제출하기", class: "btn btn-secondary submitbutton" %></div>
            <ul class="pull-left list-inline"><li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li><li><a href="">
              <i class="glyphicon glyphicon-camera"></i></a></li><li><a href="">
                <i class="glyphicon glyphicon-map-marker"></i></a></li></ul>
		    </div>	
    
      </div>
  </div>
</div>
<% end %>

<script>
  $('#user_stars').raty({
    path: '/assets',
    scoreName: 'review[star]',
    score: 1
  });
</script>

<script type="text/javascript">
  $('#review_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_modal-editinfo.html.erb
<div id="practiceModal" class="modal fade" role="dialog">
          <div class="modal-dialog">
        
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">개인정보 수정하기</h4>
              </div>
              <div class="modal-body"> <!-- 지금 로그아웃이 안 돼서 그런데, 이거 회원가입 했을때랑 똑같은 정보들로 목차 만들어야 될듯. -->
                <p>이름</p>
                 <textarea class="form-control input-lg" autofocus="" placeholder="김예은"></textarea>
                 <br>
                 <p>생년월일</p>
                 <textarea class="form-control input-lg" autofocus="" placeholder="1996/03/23"></textarea>
                 <br>
                 <p>전화번호</p>
                 <textarea class="form-control input-lg" autofocus="" placeholder="0101010101"></textarea>
                 <br>
                 <p>이메일</p>
                 <textarea class="form-control input-lg" autofocus="" placeholder="gmail.com"></textarea>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div

app/views/shared/_modal-editprice.html.erb
 <div class="modal fade" id="editpriceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                      <div class="modal-content">
                      <div class="modal-header">
                       <h5 class="modal-title" id="exampleModalLabel">가격 수정하기</h5>
                  
                       
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                       </button>
                      </div>
                      <div class="modal-body">
                       
                       <p> 항목 이름 </p>
                        <textarea class="form-control input-lg" autofocus="" placeholder="항목이름"></textarea>
                       <p> 가격 </p>
                         <textarea class="form-control input-lg" autofocus="" placeholder="가격"></textarea>
                      
                       <br>
              
                      </div>
                      <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                     <button type="button" class="btn btn-primary">저장</button>
                     </div>
                     </div>
                     </div>
                     </div>

app/views/shared/_navbar.html.erb
<div class="gnb">
<!-- .logo는 네비게이션 좌측 로고 구역 -->
  <a href="/"><div class="logo"></div></a>
  <!-- ul은 네비게이션 우측 버튼들 구역 -->
  <ul>
    <!-- 1)a onmouseout onmousemove 는 뭐지? 서로 다른 img를 링크했네?
    2) img name은 뭐지??-->
      
  <a href="#search">
    <li><i class="fa fa-search aria-hidden="true""></i>
  </li></a>
  <% if user_signed_in? %>
  <li><strong><%=current_user.name%></strong>님</li>
    <% if current_user.role == "일반고객" %>
      <li><span>  <%= link_to '마이페이지', user_path(current_user), :class => 'navbar-link' %></li>
    <% elsif current_user.role == "수의사" %>
      <% if current_user.vets.count > 0 %>
        <li><span>  <%= link_to '병원 정보 관리', edit_vet_path(current_user.vets[0].id), :class => 'navbar-link' %></li>
      <% else %>
        <li><span>  <%= link_to '병원 정보 관리', new_vet_path(current_user), :class => 'navbar-link' %></li>
      <% end %>
    <% end %>    
      <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></span></li>
<% else %>
  <li><span><%= link_to "회원가입", new_user_registration_path, :class => 'navbar-link'  %></li>
  <li><%= link_to "로그인", new_user_session_path, :class => 'navbar-link'  %></span></li>
<% end %>    
  <li><span><%= link_to '서비스소개', introduction_path, :class => 'navbar-link' %></li>
  </ul>
  <div id="search">
    <button type="button" class="close">×</button>
      <%= form_tag(search_path, local: true, method: :get, id:"mainsearch") do %>
      <%= text_field_tag(:q, nil, id: 'searchbar', placeholder: '지역,병원명 등을 검색해보세요! :D',autocomplete: "off")%>
      <%= button_tag '검색', type: 'submit', class: 'submitbtn' do %>
      <div>검색 <i class="fa fa-search aria-hidden="true""></i></div>
      <% end %>
      <% end %>    
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="gnb main-gnb">
<!-- .logo는 네비게이션 좌측 로고 구역 -->
<ul class="leftul">
  <li><a href="#pagedown1"><i class="fa fa-search" aria-hidden="true"></i></a></li>
  <li><a href="#pagedown2">리뷰작성</a></li>
  <li><a href="#pagedown3">예약</a></li>
  <li><a href="#pagedown4">최근리뷰</a></li>    
</ul>
  <div class="logo"><a href="/"></a></div>
  <!-- ul은 네비게이션 우측 버튼들 구역 -->
  <ul class="rightul">
    <!-- 1)a onmouseout onmousemove 는 뭐지? 서로 다른 img를 링크했네?
    2) img name은 뭐지??-->
<% if user_signed_in? %>
  <li><strong><%=current_user.name%></strong>님</li>
    <% if current_user.role == "일반고객" %>
      <li><span>  <%= link_to '마이페이지', user_path(current_user), :class => 'navbar-link' %></li>
    <% elsif current_user.role == "수의사" %>
      <% if current_user.vets.count > 0 %>
        <li><span>  <%= link_to '병원 정보 관리', edit_vet_path(current_user.vets[0].id), :class => 'navbar-link' %></li>
      <% else %>
        <li><span>  <%= link_to '병원 정보 관리', new_vet_path(current_user), :class => 'navbar-link' %></li>
      <% end %>
    <% end %>    
    <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
<% else %>
  <li><span><%= link_to "회원가입", new_user_registration_path, :class => 'navbar-link'  %></li>
  <li><%= link_to "로그인", new_user_session_path, :class => 'navbar-link'  %></span></li>
<% end %>   
  <li><span><%= link_to '서비스소개', introduction_path, :class => 'navbar-link' %></li>
  </ul>
  
    <!--<form action="/hospitals/show">-->
    <!--  <input type="search" value="" placeholder="리뷰를 작성할 병원명을 입력해주세요 :D" />-->
    <!--</form>-->
</div>